### ISSUE TITLE
Ամենավերին տողի ֆիքսացում

### ISSUE THREAD

**Issue by haykevorgyan** [hellooarmenia/listingpro-child#1]
Բոլոր էջերում ամենավերևի մոխրագույն helloo տողը պետք է ֆիքսենք ու բոլոր էջերում երևան helloo logo-ն, կապը և լեզուները:
![Picture1](https://user-images.githubusercontent.com/60042146/72667685-e5b9e900-3a37-11ea-8f56-e4bc40a0ede7.png)

**Comment by diazoxide** [comment]
Done
