### ISSUE TITLE
ԲԱՆԱԼԻ ԲԱՌԵՐ Պոյիսկի համար

### ISSUE THREAD

**Issue by haykevorgyan** [hellooarmenia/listingpro-child#12]
Լիստինգի Կոնտենտի հատվածում պետք է լինի մի հատված /բացել-փակել/ կոճակով, որտեղ կգրենք պոյիսկի համար անհրաժեշտ բոլոր բանալի բառերը։

**Comment by diazoxide** [comment]
@haykevorgyan its already handled.
